const graphLibrary = [
    {
      name: 'K3 (Triangle)',
      vertices: [
        { id: 0, x: 150, y: 50 },
        { id: 1, x: 250, y: 220 },
        { id: 2, x: 50, y: 220 },
      ],
      edges: [
        { source: 0, target: 1 },
        { source: 1, target: 2 },
        { source: 2, target: 0 },
      ],
      tags: ['complete'],
    },
    {
      name: 'K4',
      vertices: [
        { id: 0, x: 100, y: 50 },
        { id: 1, x: 200, y: 50 },
        { id: 2, x: 200, y: 150 },
        { id: 3, x: 100, y: 150 },
      ],
      edges: [
        { source: 0, target: 1 },
        { source: 0, target: 2 },
        { source: 0, target: 3 },
        { source: 1, target: 2 },
        { source: 1, target: 3 },
        { source: 2, target: 3 },
      ],
      tags: ['complete'],
    },
    {
      name: 'K5',
      vertices: [
        { id: 0, x: 150, y: 30 },
        { id: 1, x: 263, y: 112 },
        { id: 2, x: 220, y: 245 },
        { id: 3, x: 80, y: 245 },
        { id: 4, x: 37, y: 112 },
      ],
      edges: [
        { source: 0, target: 1 },
        { source: 0, target: 2 },
        { source: 0, target: 3 },
        { source: 0, target: 4 },
        { source: 1, target: 2 },
        { source: 1, target: 3 },
        { source: 1, target: 4 },
        { source: 2, target: 3 },
        { source: 2, target: 4 },
        { source: 3, target: 4 },
      ],
      tags: ['complete'],
    },
    {
      name: 'C4 (4-Cycle)',
      vertices: [
        { id: 0, x: 100, y: 50 },
        { id: 1, x: 200, y: 50 },
        { id: 2, x: 200, y: 150 },
        { id: 3, x: 100, y: 150 },
      ],
      edges: [
        { source: 0, target: 1 },
        { source: 1, target: 2 },
        { source: 2, target: 3 },
        { source: 3, target: 0 },
      ],
      tags: ['cycle'],
    },
    {
      name: 'C5 (5-Cycle)',
      vertices: [
        { id: 0, x: 150, y: 30 },
        { id: 1, x: 263, y: 112 },
        { id: 2, x: 220, y: 245 },
        { id: 3, x: 80, y: 245 },
        { id: 4, x: 37, y: 112 },
      ],
      edges: [
        { source: 0, target: 1 },
        { source: 1, target: 2 },
        { source: 2, target: 3 },
        { source: 3, target: 4 },
        { source: 4, target: 0 },
      ],
      tags: ['cycle'],
    },
    {
      name: 'C6 (6-Cycle)',
      vertices: [
        { id: 0, x: 150, y: 20 },
        { id: 1, x: 263, y: 85 },
        { id: 2, x: 263, y: 215 },
        { id: 3, x: 150, y: 280 },
        { id: 4, x: 37, y: 215 },
        { id: 5, x: 37, y: 85 },
      ],
      edges: [
        { source: 0, target: 1 },
        { source: 1, target: 2 },
        { source: 2, target: 3 },
        { source: 3, target: 4 },
        { source: 4, target: 5 },
        { source: 5, target: 0 },
      ],
      tags: ['cycle'],
    },
    {
      name: 'P4 (Path on 4)',
      vertices: [
        { id: 0, x: 50, y: 100 },
        { id: 1, x: 130, y: 100 },
        { id: 2, x: 210, y: 100 },
        { id: 3, x: 290, y: 100 },
      ],
      edges: [
        { source: 0, target: 1 },
        { source: 1, target: 2 },
        { source: 2, target: 3 },
      ],
      tags: ['path'],
    },
    {
      name: 'K3,3',
      vertices: [
        { id: 0, x: 80, y: 50 },
        { id: 1, x: 80, y: 150 },
        { id: 2, x: 80, y: 250 },
        { id: 3, x: 220, y: 50 },
        { id: 4, x: 220, y: 150 },
        { id: 5, x: 220, y: 250 },
      ],
      edges: [
        { source: 0, target: 3 },
        { source: 0, target: 4 },
        { source: 0, target: 5 },
        { source: 1, target: 3 },
        { source: 1, target: 4 },
        { source: 1, target: 5 },
        { source: 2, target: 3 },
        { source: 2, target: 4 },
        { source: 2, target: 5 },
      ],
      tags: ['complete bipartite'],
    },
    {
      name: 'Petersen Graph',
      vertices: [
        // Outer pentagon
        { id: 0, x: 150, y: 10 },
        { id: 1, x: 283, y: 107 },
        { id: 2, x: 232, y: 270 },
        { id: 3, x: 68, y: 270 },
        { id: 4, x: 17, y: 107 },
        // Inner pentagram
        { id: 5, x: 150, y: 80 },
        { id: 6, x: 220, y: 140 },
        { id: 7, x: 195, y: 220 },
        { id: 8, x: 105, y: 220 },
        { id: 9, x: 80, y: 140 },
      ],
      edges: [
        // Outer cycle
        { source: 0, target: 1 },
        { source: 1, target: 2 },
        { source: 2, target: 3 },
        { source: 3, target: 4 },
        { source: 4, target: 0 },
        // Inner pentagram
        { source: 5, target: 7 },
        { source: 7, target: 9 },
        { source: 9, target: 6 },
        { source: 6, target: 8 },
        { source: 8, target: 5 },
        // Spokes
        { source: 0, target: 5 },
        { source: 1, target: 6 },
        { source: 2, target: 7 },
        { source: 3, target: 8 },
        { source: 4, target: 9 },
      ],
      tags: ['famous'],
    },
    {
      name: 'Star S5',
      vertices: [
        { id: 0, x: 150, y: 150 },
        { id: 1, x: 150, y: 30 },
        { id: 2, x: 264, y: 115 },
        { id: 3, x: 220, y: 244 },
        { id: 4, x: 80, y: 244 },
        { id: 5, x: 36, y: 115 },
      ],
      edges: [
        { source: 0, target: 1 },
        { source: 0, target: 2 },
        { source: 0, target: 3 },
        { source: 0, target: 4 },
        { source: 0, target: 5 },
      ],
      tags: ['star'],
    },
    {
      name: 'Cube (Q3)',
      vertices: [
        { id: 0, x: 80, y: 60 },
        { id: 1, x: 200, y: 60 },
        { id: 2, x: 200, y: 160 },
        { id: 3, x: 80, y: 160 },
        { id: 4, x: 120, y: 100 },
        { id: 5, x: 240, y: 100 },
        { id: 6, x: 240, y: 200 },
        { id: 7, x: 120, y: 200 },
      ],
      edges: [
        { source: 0, target: 1 },
        { source: 1, target: 2 },
        { source: 2, target: 3 },
        { source: 3, target: 0 },
        { source: 4, target: 5 },
        { source: 5, target: 6 },
        { source: 6, target: 7 },
        { source: 7, target: 4 },
        { source: 0, target: 4 },
        { source: 1, target: 5 },
        { source: 2, target: 6 },
        { source: 3, target: 7 },
      ],
      tags: ['hypercube'],
    },
  ];
  
  export default graphLibrary;