#!/usr/bin/env python3
"""Build the Leaper leap-group database (all simple graphs on 1..8 vertices).

Sources: the networkx Graph Atlas for n <= 7 (Read & Wilson numbering, ids
G1..G1252) and nauty's geng for n = 8 (ids are canonical graph6 strings).

Stages (in order):
    prepare   Enumerate graphs; compute hops, leap-redundant edges,
              properties, names, layouts. Resumable: appends to
              WORK/entries.jsonl + WORK/gapin_all.txt and stops cleanly
              after --budget seconds; rerun until it prints DONE.
    gapsplit  Split GAP input into WORK/gapin_k.txt + driver WORK/gaprun_k.g.
    <run GAP on each driver:  gap -q -A -l GAPROOT WORK/gaprun_k.g >
    merge     Combine entries + GAP output; write the core (n<=7) and n=8
              datasets separately so the frontend can lazy-load them.

Lambda_2 is computed inside GAP as the subgroup generated by
{ s*s0 } union { s0^-1*s } over all hops s, for a fixed hop s0: every
even-length word in hops is a product of such pairs.
"""

import argparse
import json
import math
import os
import subprocess
import time

import networkx as nx

DEFAULT_GENG = os.path.expanduser(
    "~/.local/lib/python3.10/site-packages/sage_wheels/bin/geng")


# --------------------------------------------------------------------------
# Hop enumeration
# --------------------------------------------------------------------------

def enumerate_hops(G):
    """All hops on G as tuples p with p[i] = image of vertex i (0-indexed)."""
    n = G.number_of_nodes()
    adj = [sorted(G.neighbors(v)) for v in range(n)]
    res = []
    perm = [0] * n

    def bt(i, used):
        if i == n:
            res.append(tuple(perm))
            return
        for j in adj[i]:
            b = 1 << j
            if not used & b:
                perm[i] = j
                bt(i + 1, used | b)

    bt(0, 0)
    return res


# --------------------------------------------------------------------------
# Named graph templates
# --------------------------------------------------------------------------

def _circle(nodes, r=45.0, cx=0.0, cy=0.0, start=-math.pi / 2):
    k = len(nodes)
    return {
        v: (cx + r * math.cos(start + 2 * math.pi * i / k),
            cy + r * math.sin(start + 2 * math.pi * i / k))
        for i, v in enumerate(nodes)
    }


def _line(nodes, spacing=32.0):
    k = len(nodes)
    x0 = -spacing * (k - 1) / 2
    return {v: (x0 + spacing * i, 0.0) for i, v in enumerate(nodes)}


def _two_rows(top, bottom, spacing=36.0, gap=70.0):
    pos = {}
    for row, ys in ((top, -gap / 2), (bottom, gap / 2)):
        x0 = -spacing * (len(row) - 1) / 2
        for i, v in enumerate(row):
            pos[v] = (x0 + spacing * i, ys)
    return pos


def _from_edges(n, edges):
    G = nx.Graph()
    G.add_nodes_from(range(n))
    G.add_edges_from(edges)
    return G


def named_templates():
    """List of dicts: {name, aliases, family, G, pos, key}."""
    T = []

    def add(name, aliases, family, G, pos=None):
        T.append({"name": name, "aliases": aliases, "family": family,
                  "G": G, "pos": pos})

    # Trivial / paths
    add("K1", ["P1", "singleton", "point"], "Path", nx.empty_graph(1),
        {0: (0.0, 0.0)})
    add("P2", ["K2", "K1,1", "edge"], "Path", nx.path_graph(2),
        _line(range(2)))
    for k in range(3, 9):
        add(f"P{k}", [f"path on {k} vertices"] + (["K1,2"] if k == 3 else []),
            "Path", nx.path_graph(k), _line(range(k)))

    # Complete
    add("K3", ["C3", "triangle", "W2"], "Complete", nx.complete_graph(3),
        _circle(range(3)))
    for k in range(4, 9):
        add(f"K{k}", [f"complete graph on {k} vertices"], "Complete",
            nx.complete_graph(k), _circle(range(k)))

    # Cycles
    cyc_alias = {4: ["K2,2", "square", "2x2 grid"], 5: ["pentagon"],
                 6: ["hexagon"], 7: ["heptagon"], 8: ["octagon"]}
    for k in range(4, 9):
        add(f"C{k}", cyc_alias[k], "Cycle", nx.cycle_graph(k),
            _circle(range(k)))

    # Stars
    for k in range(3, 8):
        G = nx.star_graph(k)  # node 0 = hub, k leaves
        pos = _circle(range(1, k + 1), r=45)
        pos[0] = (0.0, 0.0)
        add(f"K1,{k}", [f"star S{k}"] + (["claw"] if k == 3 else []),
            "Bipartite", G, pos)

    # Complete bipartite (K2,2 = C4 handled above)
    for a in range(2, 5):
        for b in range(a, 9 - a):
            if (a, b) == (2, 2):
                continue
            G = nx.complete_bipartite_graph(a, b)
            alias = ["utility graph", "Thomsen graph"] if (a, b) == (3, 3) else []
            add(f"K{a},{b}", alias, "Bipartite", G,
                _two_rows(range(a), range(a, a + b)))

    # Grids / ladders
    for cols in (3, 4):
        G = nx.convert_node_labels_to_integers(
            nx.grid_2d_graph(2, cols), ordering="sorted")
        add(f"2x{cols} grid", [f"ladder L{cols}"] + (["domino"] if cols == 3 else []),
            "Grid", G, _two_rows(range(cols), range(cols, 2 * cols)))

    # Prism and cube (circular ladders)
    G = nx.circular_ladder_graph(3)
    pos = _circle(range(3), r=25)
    pos.update(_circle(range(3, 6), r=52))
    add("Prism", ["triangular prism", "C3 x K2", "CL3"], "Famous", G, pos)

    G = nx.circular_ladder_graph(4)
    pos = _circle(range(4), r=26, start=-math.pi / 2 + math.pi / 4)
    pos.update(_circle(range(4, 8), r=54, start=-math.pi / 2 + math.pi / 4))
    add("Cube", ["Q3", "C4 x K2", "3-cube", "CL4"], "Famous", G, pos)

    # Wheels (nx.wheel_graph(k) has k nodes: hub 0 + cycle of k-1)
    for k in range(5, 9):
        G = nx.wheel_graph(k)
        pos = _circle(range(1, k), r=48)
        pos[0] = (0.0, 0.0)
        add(f"W{k - 1}", [f"wheel on {k} vertices"], "Famous", G, pos)

    # Octahedron and friends
    add("Octahedron", ["K2,2,2", "cocktail party graph CP(3)"], "Famous",
        nx.octahedral_graph(), None)
    add("K2,2,2,2", ["cocktail party graph CP(4)", "16-cell"], "Famous",
        nx.complete_multipartite_graph(2, 2, 2, 2), _circle(range(8), r=50))
    add("Wagner graph", ["Moebius ladder M8", "V8"], "Famous",
        nx.circulant_graph(8, [1, 4]), _circle(range(8), r=50))
    add("Antiprism", ["square antiprism", "C8(1,2)"], "Famous",
        nx.circulant_graph(8, [1, 2]), _circle(range(8), r=50))

    # Small classics
    add("Paw", [], "Famous", _from_edges(4, [(0, 1), (1, 2), (2, 0), (0, 3)]))
    add("Diamond", ["K4 minus edge"], "Famous",
        _from_edges(4, [(0, 1), (0, 2), (1, 2), (1, 3), (2, 3)]))
    add("Bull", [], "Famous",
        _from_edges(5, [(0, 1), (1, 2), (2, 0), (1, 3), (2, 4)]))
    add("Butterfly", ["bowtie", "friendship F2"], "Famous",
        _from_edges(5, [(0, 1), (1, 2), (2, 0), (0, 3), (3, 4), (4, 0)]))
    add("House", [], "Famous",
        _from_edges(5, [(0, 1), (1, 2), (2, 3), (3, 0), (0, 4), (1, 4)]))
    add("Gem", [], "Famous",
        _from_edges(5, [(0, 1), (1, 2), (2, 3), (4, 0), (4, 1), (4, 2), (4, 3)]))
    add("Dart", [], "Famous",
        _from_edges(5, [(0, 1), (0, 2), (1, 2), (1, 3), (2, 3), (3, 4)]))
    add("Kite", [], "Famous",
        _from_edges(5, [(0, 1), (0, 2), (1, 2), (1, 3), (2, 3), (0, 4)]))
    add("Banner", [], "Famous",
        _from_edges(5, [(0, 1), (1, 2), (2, 3), (3, 0), (0, 4)]))
    add("Cricket", [], "Famous",
        _from_edges(5, [(0, 1), (1, 2), (2, 0), (0, 3), (0, 4)]))
    add("Net", [], "Famous",
        _from_edges(6, [(0, 1), (1, 2), (2, 0), (0, 3), (1, 4), (2, 5)]))
    add("Double star S2,2", ["smallest hopless balanced bipartite"], "Famous",
        _from_edges(6, [(0, 1), (0, 2), (0, 3), (1, 4), (1, 5)]))
    add("Friendship F3", ["windmill Wd(3,3)"], "Famous",
        _from_edges(7, [(0, 1), (1, 2), (2, 0), (0, 3), (3, 4), (4, 0),
                        (0, 5), (5, 6), (6, 0)]))
    add("Moser spindle", [], "Famous",
        _from_edges(7, [(0, 1), (0, 2), (1, 2), (1, 3), (2, 3),
                        (0, 4), (0, 5), (4, 5), (4, 6), (5, 6), (3, 6)]))

    for t in T:
        t["key"] = graph_key(t["G"])
    return T


def graph_key(G):
    return (G.number_of_nodes(), G.number_of_edges(),
            tuple(sorted(d for _, d in G.degree())))


class TemplateIndex:
    def __init__(self, templates):
        self.buckets = {}
        for t in templates:
            self.buckets.setdefault(t["key"], []).append(t)

    def match(self, G):
        """Return (template, mapping G_node -> template_node) or (None, None)."""
        for t in self.buckets.get(graph_key(G), []):
            gm = nx.algorithms.isomorphism.GraphMatcher(G, t["G"])
            if gm.is_isomorphic():
                return t, gm.mapping
        return None, None


class AtlasIndex:
    """Bucketed lookup: connected component (n<=7) -> atlas number."""

    def __init__(self, atlas):
        self.buckets = {}
        for i, G in enumerate(atlas):
            if G.number_of_nodes() == 0:
                continue
            self.buckets.setdefault(graph_key(G), []).append((i, G))

    def index_of(self, H):
        for i, G in self.buckets.get(graph_key(H), []):
            if nx.is_isomorphic(H, G):
                return i
        return None


# --------------------------------------------------------------------------
# Properties
# --------------------------------------------------------------------------

def girth_of(G):
    if nx.is_forest(G):
        return None
    best = None
    for src in G.nodes:
        dist = {src: 0}
        parent = {src: None}
        queue = [src]
        while queue:
            u = queue.pop(0)
            for w in G.neighbors(u):
                if w not in dist:
                    dist[w] = dist[u] + 1
                    parent[w] = u
                    queue.append(w)
                elif parent[u] != w:
                    c = dist[u] + dist[w] + 1
                    if best is None or c < best:
                        best = c
    return best


def compute_props(G):
    n = G.number_of_nodes()
    degs = sorted((d for _, d in G.degree()), reverse=True)
    connected = nx.is_connected(G) if n > 0 else True
    tri = sum(nx.triangles(G).values()) // 3
    return {
        "connected": connected,
        "components": nx.number_connected_components(G),
        "bipartite": nx.is_bipartite(G),
        "planar": bool(nx.check_planarity(G)[0]),
        "regular": len(set(degs)) <= 1,
        "forest": nx.is_forest(G),
        "tree": nx.is_tree(G),
        "girth": girth_of(G),
        "diameter": nx.diameter(G) if connected and n > 0 else None,
        "triangles": tri,
        "degrees": degs,
    }


# --------------------------------------------------------------------------
# Layout
# --------------------------------------------------------------------------

def layout_component(H, tindex):
    t, mapping = tindex.match(H)
    if t is not None and t["pos"] is not None:
        return {v: t["pos"][mapping[v]] for v in H.nodes}
    if H.number_of_nodes() == 1:
        return {next(iter(H.nodes)): (0.0, 0.0)}
    if H.number_of_nodes() <= 7:
        pos = nx.kamada_kawai_layout(H)
    else:
        pos = nx.spring_layout(H, seed=42, iterations=100)
    return {v: (45.0 * x, 45.0 * y) for v, (x, y) in pos.items()}


def layout_graph(G, tindex):
    comps = [G.subgraph(c).copy() for c in
             sorted(nx.connected_components(G), key=lambda c: (-len(c), sorted(c)))]
    placed = {}
    x_cursor = 0.0
    gap = 40.0
    for H in comps:
        pos = layout_component(H, tindex)
        xs = [p[0] for p in pos.values()]
        ys = [p[1] for p in pos.values()]
        minx, maxx = min(xs), max(xs)
        miny, maxy = min(ys), max(ys)
        for v, (x, y) in pos.items():
            placed[v] = (x_cursor + (x - minx), (y - (miny + maxy) / 2))
        x_cursor += (maxx - minx) + gap
    return {v: (round(x), round(y)) for v, (x, y) in placed.items()}


# --------------------------------------------------------------------------
# Naming
# --------------------------------------------------------------------------

def name_graph(G, gid, tindex, aindex):
    """Return (name, aliases, family)."""
    t, _ = tindex.match(G)
    if t is not None:
        return t["name"], list(t["aliases"]), t["family"]

    if not nx.is_connected(G):
        parts = []
        for c in sorted(nx.connected_components(G), key=lambda c: (-len(c), sorted(c))):
            H = nx.convert_node_labels_to_integers(
                G.subgraph(c), ordering="sorted")
            tc, _ = tindex.match(H)
            if tc is not None:
                parts.append(tc["name"])
            else:
                idx = aindex.index_of(H)
                parts.append(f"G{idx}" if idx is not None else "?")
        return " + ".join(parts), ["disjoint union"], "Disjoint union"

    if nx.is_tree(G):
        return gid, [], "Tree"
    return gid, [], "Other"


# --------------------------------------------------------------------------
# Graph sources
# --------------------------------------------------------------------------

def all_graphs(geng):
    """Yield (gid, atlas_number_or_None, G) for every simple graph, n=1..8."""
    items = []
    atlas = nx.graph_atlas_g()
    for i, G in enumerate(atlas):
        if G.number_of_nodes() == 0:
            continue
        items.append((f"G{i}", i, G))
    out = subprocess.run([geng, "-q", "8"], capture_output=True, text=True,
                         check=True)
    for line in out.stdout.split():
        G = nx.from_graph6_bytes(line.encode())
        items.append((line, None, G))
    return items, atlas


# --------------------------------------------------------------------------
# Stages
# --------------------------------------------------------------------------

def read_jsonl(path):
    """Read a JSONL file, truncating a trailing corrupt line if present."""
    if not os.path.exists(path):
        return []
    entries = []
    with open(path) as f:
        lines = f.readlines()
    bad_tail = False
    for i, line in enumerate(lines):
        line = line.strip()
        if not line:
            continue
        try:
            entries.append(json.loads(line))
        except json.JSONDecodeError:
            if i == len(lines) - 1:
                bad_tail = True
            else:
                raise
    if bad_tail:
        with open(path, "w") as f:
            for e in entries:
                f.write(json.dumps(e) + "\n")
    return entries


def stage_prepare(workdir, geng, budget):
    os.makedirs(workdir, exist_ok=True)
    t0 = time.time()
    items, atlas = all_graphs(geng)
    entries_path = os.path.join(workdir, "entries.jsonl")
    gap_path = os.path.join(workdir, "gapin_all.txt")

    done = len(read_jsonl(entries_path))
    templates = named_templates()
    tindex = TemplateIndex(templates)
    aindex = AtlasIndex(atlas)

    ef = open(entries_path, "a")
    gf = open(gap_path, "a")

    for pos in range(done, len(items)):
        if time.time() - t0 > budget:
            ef.close()
            gf.close()
            print(f"PARTIAL {pos}/{len(items)}")
            return
        gid, atlas_no, G = items[pos]
        n = G.number_of_nodes()
        hops = enumerate_hops(G)
        props = compute_props(G)

        used = set()
        for h in hops:
            for u, v in enumerate(h):
                used.add((min(u, v), max(u, v)))
        edges_sorted = sorted([sorted(e) for e in G.edges()])
        redundant = [i for i, e in enumerate(edges_sorted)
                     if tuple(e) not in used]
        core = nx.Graph()
        core.add_nodes_from(range(n))
        redset = set(redundant)
        core.add_edges_from(e for i, e in enumerate(edges_sorted)
                            if i not in redset)
        leap_connected = nx.is_connected(core)

        name, aliases, family = name_graph(G, gid, tindex, aindex)
        layout = layout_graph(G, tindex)

        entry = {
            "id": gid,
            "atlas": atlas_no,
            "g6": nx.to_graph6_bytes(G, header=False).decode().strip(),
            "name": name,
            "aliases": aliases,
            "family": family,
            "n": n,
            "m": G.number_of_edges(),
            "edges": edges_sorted,
            "layout": [list(layout[v]) for v in range(n)],
            "hopCount": len(hops),
            "hasHop": len(hops) > 0,
            "redundant": redundant,
            "leapConnected": leap_connected,
            **{k: props[k] for k in
               ("connected", "components", "bipartite", "planar", "regular",
                "forest", "tree", "girth", "diameter", "triangles", "degrees")},
        }

        if hops:
            one_indexed = [[x + 1 for x in h] for h in hops]
            gf.write(f"{gid};{json.dumps(one_indexed)}\n")
            gf.flush()
        ef.write(json.dumps(entry) + "\n")

    ef.close()
    gf.close()
    print(f"DONE {len(items)} graphs")


GAP_DRIVER = """\
stream := InputTextFile("{infile}");;
out := OutputTextFile("{outfile}", false);;
SetPrintFormattingStatus(out, false);
line := ReadLine(stream);;
while line <> fail do
  line := Chomp(line);
  semi := Position(line, ';');
  id := line{{[1..semi-1]}};
  lists := EvalString(line{{[semi+1..Length(line)]}});
  gens := List(lists, PermList);
  G1 := Group(gens);
  s0 := gens[1];
  T := Concatenation(List(gens, s -> s * s0), List(gens, s -> s0^-1 * s));
  G2 := Group(T);
  AppendTo(out, id, ";", Order(G1), ";", StructureDescription(G1), ";",
    IsAbelian(G1), ";", Order(G2), ";", StructureDescription(G2), ";",
    IsAbelian(G2), "\\n");
  line := ReadLine(stream);
od;
CloseStream(out);
QUIT;
"""


def stage_gapsplit(workdir, n_chunks):
    jobs = {}
    with open(os.path.join(workdir, "gapin_all.txt")) as f:
        for line in f:
            line = line.rstrip("\n")
            if not line:
                continue
            gid = line.split(";", 1)[0]
            jobs[gid] = line  # keep last occurrence

    ordered = sorted(jobs.values(), key=len, reverse=True)
    chunks = [[] for _ in range(n_chunks)]
    loads = [0] * n_chunks
    for line in ordered:
        k = loads.index(min(loads))
        chunks[k].append(line)
        loads[k] += len(line)

    for k, chunk in enumerate(chunks):
        inpath = os.path.join(workdir, f"gapin_{k}.txt")
        outpath = os.path.join(workdir, f"gapout_{k}.txt")
        with open(inpath, "w") as f:
            f.write("\n".join(chunk) + "\n")
        with open(os.path.join(workdir, f"gaprun_{k}.g"), "w") as f:
            f.write(GAP_DRIVER.format(infile=inpath, outfile=outpath))
    print(f"split {len(jobs)} GAP jobs into {n_chunks} chunks")


def stage_merge(workdir, out_core, out_n8, n_chunks):
    raw = read_jsonl(os.path.join(workdir, "entries.jsonl"))
    entries = {}
    for e in raw:
        entries[e["id"]] = e  # keep last occurrence
    entries = list(entries.values())

    results = {}
    for k in range(n_chunks):
        p = os.path.join(workdir, f"gapout_{k}.txt")
        if not os.path.exists(p):
            continue
        with open(p) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                gid, o1, d1, a1, o2, d2, a2 = line.split(";")
                results[gid] = {
                    "l1Order": int(o1), "l1": d1, "l1Abelian": a1 == "true",
                    "l2Order": int(o2), "l2": d2, "l2Abelian": a2 == "true",
                }

    missing = 0
    for e in entries:
        if e["hasHop"]:
            r = results.get(e["id"])
            if r is None:
                missing += 1
                continue
            e.update(r)
            e["reclusive"] = r["l1Order"] == r["l2Order"]
        else:
            e.update({"l1Order": 1, "l1": "1", "l1Abelian": True,
                      "l2Order": 1, "l2": "1", "l2Abelian": True,
                      "reclusive": False})

    if missing:
        raise SystemExit(f"ERROR: {missing} entries missing GAP results")

    core = [e for e in entries if e["n"] <= 7]
    n8 = [e for e in entries if e["n"] == 8]
    core.sort(key=lambda e: e["atlas"])
    n8.sort(key=lambda e: e["g6"])

    for path, data in ((out_core, core), (out_n8, n8)):
        with open(path, "w") as f:
            json.dump(data, f, separators=(",", ":"))
        print(f"wrote {len(data)} entries to {path} "
              f"({os.path.getsize(path)} bytes)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("stage", choices=["prepare", "gapsplit", "merge"])
    ap.add_argument("--workdir", required=True)
    ap.add_argument("--geng", default=DEFAULT_GENG)
    ap.add_argument("--budget", type=float, default=1e9,
                    help="prepare: stop cleanly after this many seconds")
    ap.add_argument("--chunks", type=int, default=40)
    ap.add_argument("--out-core", default="leapDatabaseCore.json")
    ap.add_argument("--out-n8", default="leapDatabaseN8.json")
    args = ap.parse_args()
    if args.stage == "prepare":
        stage_prepare(args.workdir, args.geng, args.budget)
    elif args.stage == "gapsplit":
        stage_gapsplit(args.workdir, args.chunks)
    else:
        stage_merge(args.workdir, args.out_core, args.out_n8, args.chunks)


if __name__ == "__main__":
    main()
