/**
 * Search and filter utilities for the leap group database.
 *
 * The database itself (src/data/leapDatabase.json) is generated by
 * scripts/database/build_database.py — see scripts/database/README.md.
 */

/**
 * Normalize a group-structure string for matching, so that user input like
 * "Z2 x Z2", "C2×C2", or "c2xc2" all match GAP's "C2 x C2".
 * Also maps ⋊ (semidirect) to GAP's ":".
 */
export function normalizeGroup(s) {
  return s
    .toLowerCase()
    .replace(/[×✕⨯*]/g, 'x')
    .replace(/[⋊⋉]/g, ':')
    .replace(/z(?=\d)/g, 'c')     // Zn -> Cn
    .replace(/[\s_().]/g, '');
}

/**
 * Normalize a graph-name string: lowercase, strip spaces, ×->x, ⊔/∪->+.
 * Disjoint-union names have their components sorted, so "C3 + C5" matches
 * the database's "C5 + C3".
 */
// Doubly-named small graphs, canonicalized inside disjoint-union names so
// "C3 + C5" matches the database's "C5 + K3".
const COMPONENT_SYNONYMS = {
  triangle: 'c3', k3: 'c3',
  edge: 'p2', k2: 'p2', 'k1,1': 'p2',
  p1: 'k1', singleton: 'k1',
  square: 'c4', 'k2,2': 'c4',
};

function normalizeName(s) {
  const norm = s
    .toLowerCase()
    .replace(/[×✕⨯]/g, 'x')
    .replace(/[⊔∪]/g, '+')
    .replace(/[\s_]/g, '');
  if (norm.includes('+')) {
    return norm
      .split('+')
      .map((p) => COMPONENT_SYNONYMS[p] || p)
      .sort()
      .join('+');
  }
  return norm;
}

/**
 * Attach precomputed lowercase search blobs to an entry. With 13.6k entries,
 * normalizing on every keystroke is too slow; this runs once at load time.
 * Fields are space-separated; normalized queries contain no spaces, so a
 * substring match cannot straddle two fields.
 */
export function prepEntry(e) {
  return {
    ...e,
    _name: [normalizeName(e.name), ...e.aliases.map(normalizeName),
            e.id.toLowerCase()].join(' '),
    _l1: normalizeGroup(e.l1),
    _l2: normalizeGroup(e.l2),
  };
}

/** Does a prepped `entry` match the free-text query under the given mode? */
export function matchesQuery(entry, query, mode) {
  const q = query.trim();
  if (!q) return true;

  const nameHit = () => {
    if (entry._name.includes(normalizeName(q))) return true;
    return entry.g6 === q; // graph6 is case-sensitive; match raw
  };

  const groupHit = () => {
    const gq = normalizeGroup(q);
    if (!gq) return false;
    if (entry._l1.includes(gq) || entry._l2.includes(gq)) return true;
    // A bare number matches the group order exactly
    if (/^\d+$/.test(q)) {
      return entry.l1Order === Number(q) || entry.l2Order === Number(q);
    }
    return false;
  };

  if (mode === 'name') return nameHit();
  if (mode === 'group') return groupHit();
  return nameHit() || groupHit();
}

/** Tri-state helper: state is 'any' | 'yes' | 'no'. */
function triPass(state, value) {
  if (state === 'any') return true;
  return state === 'yes' ? !!value : !value;
}

export const MAX_N = 8;

export const DEFAULT_FILTERS = {
  minN: 1,
  maxN: MAX_N,
  family: 'any',
  hasHop: 'any',
  connected: 'any',
  bipartite: 'any',
  reclusive: 'any',
  planar: 'any',
  regular: 'any',
  forest: 'any',
  l1Abelian: 'any',
  leapConnected: 'any',
};

export function passesFilters(entry, f) {
  if (entry.n < f.minN || entry.n > f.maxN) return false;
  if (f.family !== 'any' && entry.family !== f.family) return false;
  return (
    triPass(f.hasHop, entry.hasHop) &&
    triPass(f.connected, entry.connected) &&
    triPass(f.bipartite, entry.bipartite) &&
    triPass(f.reclusive, entry.reclusive) &&
    triPass(f.planar, entry.planar) &&
    triPass(f.regular, entry.regular) &&
    triPass(f.forest, entry.forest) &&
    triPass(f.l1Abelian, entry.l1Abelian) &&
    triPass(f.leapConnected, entry.leapConnected)
  );
}

// Stable tiebreak: atlas number for n <= 7, then graph6 (n = 8 has no
// atlas numbering).
const tie = (a, b) =>
  (a.atlas ?? Infinity) - (b.atlas ?? Infinity) || a.g6.localeCompare(b.g6);

export const SORTS = {
  vertices: {
    label: 'Vertices',
    cmp: (a, b) => a.n - b.n || a.m - b.m || tie(a, b),
  },
  hops: {
    label: 'Most hops',
    cmp: (a, b) => b.hopCount - a.hopCount || a.n - b.n || tie(a, b),
  },
  order: {
    label: 'Largest Λ₁',
    cmp: (a, b) => b.l1Order - a.l1Order || a.n - b.n || tie(a, b),
  },
  name: {
    label: 'Name',
    cmp: (a, b) => a.name.localeCompare(b.name, undefined, { numeric: true }),
  },
};

export function searchDatabase(db, query, mode, filters, sortKey) {
  const out = db.filter(
    (e) => passesFilters(e, filters) && matchesQuery(e, query, mode)
  );
  out.sort(SORTS[sortKey].cmp);
  return out;
}
